# -*- coding: utf-8 -*-

##### Auto-update version.py
import os
import subprocess


# Fetch version from git describe and write it to version.py
version_py = os.path.join(os.path.dirname(__file__), "ksiga", "version.py")

try:
    version_git = subprocess.check_output(["git", "describe", "--tags"]).rstrip().replace('v', '')
    version_git = version_git.decode("utf-8")
except:
    with open(version_py, "r") as fh:
        version_git = open(version_py).read().strip().split("=")[-1].replace('"', '')

version_msg = "# Do not edit this file, pipeline versioning is governed by git tags"
with open(version_py, "w") as fh:
    fh.write(version_msg + os.linesep + "version=" + '"' + version_git + '"')

##### Setup
from setuptools import setup, find_packages

def readme():
    with open('README.rst') as f:
        return f.read()

setup(
    name='ksiga',
    version="{ver}".format(ver=version_git),
    description='tools for finding an optimal kmer',
    long_description=readme(),
    classifiers=[
        'Development Status :: 4 - Beta',
        'License :: OSI Approved :: Apache Software License',
        'Programming Language :: Python :: 3.6',
        'Topic :: Scientific/Engineering :: Bio-Informatics',
    ],
    keywords='ksiga',
    url='https://gitlab.com/natapol.por/ksiga',
    packages=['ksiga'],
    author='Natapol Pornputtapong, Preecha Patumcharoenpol',
    author_email='natapol.por@gmail.com',
    license="Apache 2.0",
    scripts=["bin/jellyfish-linux", "bin/jellyfish-macosx"],
    entry_points = {
        'console_scripts': ['ksiga=ksiga.main:main'],
    },
    test_suite='nose.collector',
    tests_require=['nose', 'nose-cover3'],
    include_package_data=True,
    install_requires=["numpy >= 1.1.0",
                        "scipy>=0.18.1",
                        "biopython>=1.68",
                        "tqdm"
                    ],
    zip_safe=False
)
